describe('Lettobet.com', () => {

    it('Lettobet.com', () => {

        cy.visit('https://lettobet.com/')
        cy.viewport(1920, 1080).wait(3000)


        /*Auth*/
        cy.get('#root > :nth-child(2) > :nth-child(1) > :nth-child(3) > :nth-child(2) > :nth-child(1)')
            .click()
        cy.get('#login_username_input')
            .type('kemuro')
        cy.get('#login_password_input')
            .type('kemuro')
        cy.get('#login_button')
            .click()
            .wait(3000)

        /*Sport*/
        cy.get('#root > :nth-child(2) > :nth-child(2) > :nth-child(1)')
            .click().wait(20000)
        cy.get('#outcome-2121745631243542528-1--1' )
            .click()


        /*Live*/
        cy.get('#root > :nth-child(2) > :nth-child(2) > :nth-child(2)')
            .click().wait(10000)

        /*Virtual games*/
        cy.get('#root > :nth-child(2) > :nth-child(2) > :nth-child(3)')
            .click().wait(2000)
        cy.get('#root > :nth-child(3) > :nth-child(1) > :nth-child(3) > :nth-child(1) > :nth-child(1) > :nth-child(3)')
            .click().wait(5000)
        /*Games*/
        /*Poisk*/
        cy.get('#root > :nth-child(2) > :nth-child(2) > :nth-child(4)')
            .click().wait(2000)
        cy.get('#desktop-games-main-container > :nth-child(2) > :nth-child(1) > :nth-child(1) > :nth-child(1) > :nth-child(1) > :nth-child(1) > :nth-child(1)')
            .type('shark').wait(2000)
        cy.get('#root > :nth-child(3) > :nth-child(1) > :nth-child(3) > :nth-child(1) > :nth-child(1) > :nth-child(3) > :nth-child(2) > :nth-child(1) > :nth-child(1) > :nth-child(1) > :nth-child(1) > :nth-child(1) > :nth-child(1)')
            .click().wait(7000)
        /*Find provider*/
        cy.get('#root > :nth-child(2) > :nth-child(2) > :nth-child(4)')
            .click().wait(2000)
        cy.get('#root > :nth-child(3) > :nth-child(1) > :nth-child(2) > :nth-child(2) > :nth-child(1) > :nth-child(1)')
            .click().wait(2000)
        cy.get('#root > :nth-child(3) > :nth-child(1) > :nth-child(2) > :nth-child(2) > :nth-child(1) > :nth-child(11) > :nth-child(1)')
            .click().wait(2000)
        cy.get('#root > :nth-child(3) > :nth-child(1) > :nth-child(2) > :nth-child(2) > :nth-child(1) > :nth-child(1)')
            .click().wait(2000)
        cy.get('#root > :nth-child(3) > :nth-child(1) > :nth-child(3) > :nth-child(1) > :nth-child(2) > :nth-child(4)')
            .click().wait(7000)
        /*Favourite/Unfavourite games*/
        cy.get('#root > :nth-child(2) > :nth-child(2) > :nth-child(4)')
            .click().wait(2000)
        cy.get('#root > :nth-child(3) > :nth-child(1) > :nth-child(2) > :nth-child(3) > :nth-child(1) > :nth-child(1) > :nth-child(1) > :nth-child(2) > :nth-child(1)')
            .click().wait(3000)
        cy.get('#root > :nth-child(3) > :nth-child(1) > :nth-child(2) > :nth-child(2) > :nth-child(1) > :nth-child(1)')
            .click().wait(2000)
        cy.get('#root > :nth-child(3) > :nth-child(1) > :nth-child(2) > :nth-child(2) > :nth-child(1) > :nth-child(20) > :nth-child(1)')
            .click()
        cy.get('#root > :nth-child(3) > :nth-child(1) > :nth-child(2) > :nth-child(2) > :nth-child(1) > :nth-child(1)')
            .click().wait(2000)
        cy.get('#root > :nth-child(3) > :nth-child(1) > :nth-child(2) > :nth-child(3) > :nth-child(1) > :nth-child(1) > :nth-child(1) > :nth-child(1) > :nth-child(1)')
            .click().wait(3000)
        cy.get('#root > :nth-child(3) > :nth-child(1) > :nth-child(2) > :nth-child(2) > :nth-child(1) > :nth-child(1)')
            .click().wait(2000)
        cy.get('#root > :nth-child(3) > :nth-child(1) > :nth-child(2) > :nth-child(2) > :nth-child(1) > :nth-child(20) > :nth-child(1)')
            .click()
        cy.get('#root > :nth-child(3) > :nth-child(1) > :nth-child(2) > :nth-child(2) > :nth-child(1) > :nth-child(1)')
            .click().wait(2000)
        cy.get('#root > :nth-child(3) > :nth-child(1) > :nth-child(3) > :nth-child(1) > :nth-child(2) > :nth-child(2) > :nth-child(2) > :nth-child(2) > :nth-child(1) > :nth-child(1)')
            .click().wait(1000)
        cy.get('#root > :nth-child(3) > :nth-child(1) > :nth-child(3) > :nth-child(1) > :nth-child(2) > :nth-child(4) > :nth-child(2) > :nth-child(2) > :nth-child(1) > :nth-child(1)')
            .click().wait(1000)
        cy.get('#root > :nth-child(3) > :nth-child(1) > :nth-child(3) > :nth-child(1) > :nth-child(2) > :nth-child(6) > :nth-child(2) > :nth-child(2) > :nth-child(1) > :nth-child(1)')
            .click().wait(1000)
        cy.get('#root > :nth-child(3) > :nth-child(1) > :nth-child(2) > :nth-child(3) > :nth-child(1) > :nth-child(1) > :nth-child(1) > :nth-child(2) > :nth-child(1)')
            .click().wait(3000)

        /*TV Games*/
        cy.get('#root > :nth-child(2) > :nth-child(2) > :nth-child(5)')
            .click().wait(2000)
        cy.get('#root > :nth-child(3) > :nth-child(1) > :nth-child(3) > :nth-child(1) > :nth-child(4)')
            .click().wait(2000)
        cy.get('#root > :nth-child(3) > :nth-child(1) > :nth-child(4) > :nth-child(1) > :nth-child(1) > :nth-child(1) > :nth-child(3) > :nth-child(1) > :nth-child(1) > :nth-child(1) > :nth-child(1) > :nth-child(1) > :nth-child(6) > :nth-child(1) > :nth-child(1) > :nth-child(1)')
            .click().wait(7000)

        /*Promotions*/
        cy.get('#root > :nth-child(2) > :nth-child(2) > :nth-child(8)')
            .click().wait(2000)
        cy.get('#root > :nth-child(3) > :nth-child(1) > :nth-child(2) > :nth-child(1) > :nth-child(1) > :nth-child(1)')
            .click().wait(2000)
        cy.get('#modal-root > :nth-child(1) > :nth-child(1) > :nth-child(1) > :nth-child(1) > :nth-child(1) > :nth-child(1) > :nth-child(1) > :nth-child(1) > :nth-child(1)')
            .click().wait(2000)

        /*Turbo games*/
        cy.get('#root > :nth-child(2) > :nth-child(2) > :nth-child(9)')
            .click().wait(2000)
        cy.get('#root > :nth-child(3) > :nth-child(1) > :nth-child(3) > :nth-child(1) > :nth-child(1) > :nth-child(5)')
            .click().wait(7000)

        /*Log out*/
        cy.get('#root > :nth-child(2) > :nth-child(1) > :nth-child(3) > :nth-child(1) > :nth-child(3) > :nth-child(3) > :nth-child(1) > :nth-child(2) > :nth-child(1) > :nth-child(2)')
            .click()
        cy.get('#sidebar_logout')
            .click()






        /* cy.get('#header_menu_Games > a > .SecondHeader__Item-sc-1knw2af-2')
             .click()
             .wait(3000)
         cy.get('.Providers__Wrapper-sc-1lrin2a-0 > .bjBSWf')
             .click()
             .wait(2000)
         cy.get(':nth-child(11) > .Providers__Image-sc-1lrin2a-1')
             .click()
         cy.get('.Providers__Wrapper-sc-1lrin2a-0 > .bjBSWf')
             .click()
             .wait(5000)

         cy.get(':nth-child(1) > .GameCard__ImageContainer-sc-16o4gu2-1 > .lazy-load-image-background > .GameCard__GameImage-sc-16o4gu2-4')
             .click()
             .wait(35000)
         cy.get('#header_menu_Games > a > .SecondHeader__Item-sc-1knw2af-2')
             .click()
             .wait(3000)
         cy.get('.Providers__Wrapper-sc-1lrin2a-0 > .bjBSWf')
             .click()
             .wait(2000)
         cy.get(':nth-child(43) > .Providers__Image-sc-1lrin2a-1')
             .click()
         cy.get('.Providers__Wrapper-sc-1lrin2a-0 > .bjBSWf')
             .click()
             .wait(5000)
         cy.get(':nth-child(3) > .GameCard__ImageContainer-sc-16o4gu2-1 > .lazy-load-image-background > .GameCard__GameImage-sc-16o4gu2-4')
             .click()
             .wait(20000)

         cy.get('#header_menu_TV\\ Games > a > .SecondHeader__Item-sc-1knw2af-2')
             .click()
             .wait(3000)
         cy.get(':nth-child(4) > .Providers__Image-sc-1lrin2a-1')
             .click()
             .wait(2000)
         cy.get('[style="position: absolute; left: 547px; top: 20px; height: 218px; width: 245px;"] > .GameCard__ImageContainer-sc-16o4gu2-1 > .lazy-load-image-background > .GameCard__GameImage-sc-16o4gu2-4')
             .click()
             .wait(15000)
         cy.get('#header_menu_TV\\ Games > a > .SecondHeader__Item-sc-1knw2af-2')
             .click()
             .wait(3000)
         cy.get(':nth-child(4) > .Providers__Image-sc-1lrin2a-1')
             .click()
             .wait(2000)
         cy.get('[style="position: absolute; left: 814px; top: 238px; height: 218px; width: 245px;"] > .GameCard__ImageContainer-sc-16o4gu2-1 > .lazy-load-image-background > .GameCard__GameImage-sc-16o4gu2-4')
             .click()
             .wait(15000)
         cy.get('#header_menu_TV\\ Games > a > .SecondHeader__Item-sc-1knw2af-2')
             .click()
             .wait(9000)
         cy.get(':nth-child(4) > .Providers__Image-sc-1lrin2a-1')
             .click()
             .wait(2000)
         cy.get(':nth-child(6) > .Providers__Image-sc-1lrin2a-1')
             .click()
         cy.get('[style="position: absolute; left: 13px; top: 238px; height: 218px; width: 245px;"] > .GameCard__ImageContainer-sc-16o4gu2-1 > .lazy-load-image-background > .GameCard__GameImage-sc-16o4gu2-4')
             .click()
             .wait(15000)
         cy.get('#header_menu_Sport > a > .SecondHeader__Item-sc-1knw2af-2')
             .click()
             .wait(15000)

         cy.get('#header_menu_Virtual\\ games > a > .SecondHeader__Item-sc-1knw2af-2')
             .click()
             .wait(10000)
         cy.get(':nth-child(15) > .GameCard__ImageContainer-sc-16o4gu2-1 > .lazy-load-image-background > .GameCard__GameImage-sc-16o4gu2-4')
             .click()
             .wait(10000)

         cy.get('#header_menu_Live > a > .SecondHeader__Item-sc-1knw2af-2')
             .click()
             .wait(10000)

         cy.get('#header_menu_Evolution > a > .SecondHeader__Item-sc-1knw2af-2')
             .click()
             .wait(3000)

         cy.get('#header_menu_Favorite\\ games > .SecondHeader__Item-sc-1knw2af-2')
             .click()
             .wait(3000)

         cy.get('#header_menu_Promotions > a > .SecondHeader__Item-sc-1knw2af-2')
             .click()
             .wait(3000)
         cy.get(':nth-child(1) > .PromotionCard__PromotionImage-sc-1qpnd0f-1')
             .click()
             .wait(1000)
         cy.get('.PromotionModal__ModalWrapper-sc-1n1d6qx-0 > .StyledButton__CustomButton-sc-12rd7py-0')
             .click()
             .wait(1000)
         cy.get('#header_menu_Promotions > a > .SecondHeader__Item-sc-1knw2af-2')
             .click()
             .wait(3000)
         cy.get(':nth-child(5) > .PromotionCard__PromotionImage-sc-1qpnd0f-1')
             .click()
             .wait(1000)
         cy.get('.PromotionModal__ModalWrapper-sc-1n1d6qx-0 > .StyledButton__CustomButton-sc-12rd7py-0')
             .click()
             .wait(1000)

         cy.get('#header_menu_TurboGames > a > .SecondHeader__Item-sc-1knw2af-2')
             .click()
             .wait(1000)
         cy.get(':nth-child(4) > .GameCard__ImageContainer-sc-16o4gu2-1 > .lazy-load-image-background > .GameCard__GameImage-sc-16o4gu2-4')
             .click()
             .wait(15000)

         cy.get('#header_logo')
             .click()
             .wait(1000)
         cy.get('.UserContainer__UserWrapper-sc-88h8ei-4')
             .click()
             .wait(1000)
         cy.get('#sidebar_logout')
             .click()*/
    })
})